### ISSUE TITLE
Not clear how to get output after loading a model

### ISSUE THREAD

**Issue by hinerm** [fiji/Trainable_Segmentation#1]
If I load a classifier model, the `Create result` button remains grayed out.

If I try to `Plot result`, I get an error message:
> No data available yet to display results

I can run `Get probability`, but it doesn't make the `Create` or `Plot` options work.

**Comment by iarganda** [comment]
Thanks @hinerm, everything is fixed in the new release. "Plot result" only works if you have training samples, so either you load some data from file or trace samples from at least two classes.
