### ISSUE TITLE
How to use several images in segmentation?

### ISSUE THREAD

**Issue by mrgloom** [fiji/Trainable_Segmentation#12]
As I understand, as shown in tutorial, Trainable Weka Segmentation can only work with one 2D image, but how can I mark several images and train one classifer for all of them?

If I can't do it through interface, maybe I can do it by making changes in code?

Also it will be great that after marking one image I can apply some kind of online / iterative learning algorithm if it possible.
seems there are some such algorithms in weka
http://www.cs.waikato.ac.nz/ml/weka/bigdata.html

**Comment by iarganda** [comment]
Hello @mrgloom , 

Yes, you can train on several 2D images at the same time using the GUI. You just need to load them all first as a stack in Fiji. Each slice of the stack will be treated as a separate image by the plugin.

Regarding the online/iterative learning algorithms, you can choose any algorithm available in Weka if you click on the Settings button of the plugin GUI.

I hope this helps!

**Comment by mrgloom** [comment]
Yes, I tried stack, but to combine images to stack I need to load all images to RAM, is there any workaround to process all images, but loading only one image at one time to RAM?

**Comment by iarganda** [comment]
Unfortunately, that option is not implemented in the GUI. Noted for my TODO list. You can also open an issue here if you want. Thanks for the feedback!
