### ISSUE TITLE
Original image and slices.

### ISSUE THREAD

**Issue by mrgloom** [fiji/Trainable_Segmentation#13]
When I don't choose any features in settings and use SGD as a classifier I get something like

```
        -2.1341 (normalized) original
 +       0.3665 (normalized) Hue
 +       5.0615 (normalized) Saturation
 +       3.2322 (normalized) Brightness
 -       2.21  
```

As I understand I we have "score"  for each "feature slice" which is add via `wholeStack.addSlice`

I wonder what is the 'original' ? is it gray or it's RGB, if RGB why it's treated as one slice?

Also as I understand magnitude of values of each slice in disicion boundary of linear classifier (SGD) representing the "importance" of each feature, but what does the sign means?

**Comment by mrgloom** [comment]
Also when I save slices as multipage tiff file, even slices that have 1 channels(for example H,S,V components) saved as 3 channel images.

**Comment by iarganda** [comment]
Hello @mrgloom 

Let me go through your questions in order:

For grayscale images the feature "original" is the input image itself, but for RGB images that feature is calculated as a combination of its channels following this formula: value=r/3+g/3+b/3 

Regarding the sign of the weight of each feature, remember that in [Stochastic Gradient Descent](https://en.wikipedia.org/wiki/Stochastic_gradient_descent) you are minimizing an objective function with the form of a sum, so the weights can have any sign. Their absolute value can give you an idea of how important they are but you can also use a Random Forest and have a look at the [variable importance](https://en.wikipedia.org/wiki/Random_forest#Variable_importance).

Finally, regarding the multipage tiff files, the plugin only understands either regular grayscale or RGB 2D images (or stacks) which in Fiji correspond to 8-bit, 16-bit, 32-bit and RGB color image types.

I hope this helps!
