### ISSUE TITLE
User input mask can be saved or loaded?

### ISSUE THREAD

**Issue by mrgloom** [fiji/Trainable_Segmentation#14]
Can we save user input labels as some mask? And can we load masks from files somehow?

**Comment by iarganda** [comment]
So far you can only do that programatically using a method like [addBinaryData](https://github.com/fiji/Trainable_Segmentation/blob/master/src/main/java/trainableSegmentation/WekaSegmentation.java#L2295). You have some scripting examples on the Fiji wiki under [Scripting the Trainable Segmentation](http://fiji.sc/Scripting_the_Trainable_Segmentation#Adding_training_samples).

From the GUI, what you can do right now is to save all ROIs belonging to a specific class into a file using the ROI manager, and load them back whenever you need them.
