### ISSUE TITLE
Missing information on installation

### ISSUE THREAD

**Issue by Sciss** [fiji/Trainable_Segmentation#17]
Hi. How do I build this project and add it to the Weka GUI application? Neither the README nor the website say anything about this. If I have `target/Trainable_Segmentation-2.3.1-SNAPSHOT.jar`, what do I do with this file to register it with Weka?

**Comment by iarganda** [comment]
Hello @Sciss 
This project is intended to be used from [Fiji](http://fiji.sc/Fiji), a general purpose image processing toolbox. What you can do is to store the feature vectors created by the Trainable Weka Segmentation GUI into ARFF files that you can then open from the Weka GUI. Does it make sense?

**Comment by Sciss** [comment]
Oh ok. That's fine, I just want to play around with the segmentation. How would I install this plugin from within ImageJ? Or is it already include it (couldn't find it from the menu yet).

**Comment by iarganda** [comment]
You just need to install Fiji :)
