### ISSUE TITLE
Loading a 3D-trained classifier fails

### ISSUE THREAD

**Issue by stelfrich** [fiji/Trainable_Segmentation#32]
When trying to load a 3D-trained classifier, either via UI or via a macro/script, the following exceptions is thrown:

```
java.lang.NumberFormatException: For input string: "ucture"
	java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	java.lang.Integer.parseInt(Integer.java:580)
	java.lang.Integer.parseInt(Integer.java:615)
	trainableSegmentation.WekaSegmentation.adjustSegmentationStateToData(WekaSegmentation.java:3995)
	trainableSegmentation.WekaSegmentation.loadClassifier(WekaSegmentation.java:707)
	trainableSegmentation.Weka_Segmentation.loadClassifier(Weka_Segmentation.java:1854)
	trainableSegmentation.Weka_Segmentation$1$1.run(Weka_Segmentation.java:399)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	java.lang.Thread.run(Thread.java:745)

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at trainableSegmentation.WekaSegmentation.adjustSegmentationStateToData(WekaSegmentation.java:3995)
	at trainableSegmentation.WekaSegmentation.loadClassifier(WekaSegmentation.java:707)
	at trainableSegmentation.Weka_Segmentation.loadClassifier(Weka_Segmentation.java:1854)
	at trainableSegmentation.Weka_Segmentation$1$1.run(Weka_Segmentation.java:399)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is due to the fact, that [`WekaSegmentation.adjustSegmentationStateToData`](https://github.com/fiji/Trainable_Segmentation/blob/master/src/main/java/trainableSegmentation/WekaSegmentation.java#L3990-L4056) interprets the used features according to `FeatureStack` instead of `FeatureStack3D`.

**Comment by iarganda** [comment]
Hello @stelfrich , I am not able to reproduce the error. Did you try to load the 3d classifier from the GUI of "Trainable Weka Segmentation 3D" or the regular "Trainable Weka Segmentation"?

**Comment by stelfrich** [comment]
It actually first noticed when loading from a script, @iarganda. But then I checked with the GUI and can reproduce the issue:

1) Start Trainable Weka Segmentation 3D
2) Select image (coincidentially the one I have trained on)
3) Click `Load classifier` and select the _*.model_ file

Looking at the source code it also makes sense that this error pops up, since `adjustSegmentationStateToData` does not differ between 2D and 3D cases in [L3990-L4056](https://github.com/fiji/Trainable_Segmentation/blob/master/src/main/java/trainableSegmentation/WekaSegmentation.java#L3990-L4056).

Maybe you are not triggering the issue because your classifier does not contain the _Structure_ feature? Could you enable all features for the classifier and check again?

**Comment by iarganda** [comment]
You are completely right! Thanks for pointing this out. I will check your changes and merge them as soon as I can.

**Comment by iarganda** [comment]
OK, I made some changes to your pull request and everything should work now. Thank you very much, @stelfrich !
