### ISSUE TITLE
Problems with load classifier

### ISSUE THREAD

**Issue by DinaSkp** [fiji/Trainable_Segmentation#34]
Hello!

I'm using Java 8 and the latest plugin version (3.2.5) and I still have problem using the load classifier option in the plugin "Trainable Weka Segmentation".
When I try to load the classifier that I've just saved to apply it on another image, nothing happens. 
In the log it says "Loading Weka classifier from ..." and when I double click on that line a dialog box open saying "File is not in a supported format, a reader plugin is not available, or it was not found".

![error fiji](https://cloud.githubusercontent.com/assets/25851735/23138602/55864eb6-f776-11e6-85eb-4104ded8bd22.png)

Do you have any idea what the problem could be?

Thanks in advance.

Dina

**Comment by iarganda** [comment]
The second error is just a common Fiji message whenever you double click on text in the Log window. Nothing related to the original problem. Regarding the first error, could it be that the classifier just takes long on loading? How large is it?

**Comment by DinaSkp** [comment]
It's 1.7 Go. Maybe it's too large...

**Comment by iarganda** [comment]
It could be that, just check if the CPU is running while you wait ;)

**Comment by DinaSkp** [comment]
I think it's still loading. Does the number / size of images, or maybe th number of region I use to train the classifier impact on its size?

**Comment by iarganda** [comment]
It mostly depends on the classifier you use, the number of features and the difficulty of the classification task. If you use a random forest (the default classifier), it might be large if you use many trees and the task is hard, because the trees are not trimmed by default.

**Comment by DinaSkp** [comment]
OK! Good to know. Thanks

**Comment by DinaSkp** [comment]
So, I've reduced the number of trees. It led to marginal effects in segmentation performance while significantly decreasing processing time and memory usage. Also it resolve the problem with the time to load the saved classifier. 
Thank you so much for the help and rapid feedback!

**Comment by iarganda** [comment]
Thank you for reporting!
