### ISSUE TITLE
Test JAR file is huge

### ISSUE THREAD

**Issue by ctrueden** [fiji/Trainable_Segmentation#37]
As of 519f21b534fa20d9f4d1756bdefdf1f9944c0236, the repository blew up by 76M, and the `Trainable_Segmentation-x.y.z-SNAPSHOT-tests.jar` now weighs in at 66M.

Would it be possible to somehow test that the features are correct, without needing the 76M `features-expected.tiff`? Or at least without bundling it into the `tests` JAR which gets deployed to the remote Maven repository every time?

**Comment by iarganda** [comment]
I agree.

@maarzt can you please change your test or use a smaller image? Thanks!

**Comment by ctrueden** [comment]
Do you want to purge it from the git history, too? Or you don't care enough?

**Comment by ctrueden** [comment]
OK, I see your thumbs up. If you want me to purge it, then afterward you (and everyone) will need to `git checkout master && git fetch && git reset --hard origin/master` to get back in sync. I will also need to rewrite a couple of tags. Is that all OK?
