### ISSUE TITLE
API offline

### ISSUE THREAD

**Issue by half-adder** [fiji/Trainable_Segmentation#48]
The API linked to in the documentation seems to be offline.

**Comment by ctrueden** [comment]
Which docs? A web URL? Can you give a link? Where does the bad link point?

**Comment by half-adder** [comment]
Sure. 

It's linked to [here](https://imagej.net/Trainable_Weka_Segmentation#Library_use). The link points [here](http://javadoc.imagej.net/Fiji/trainableSegmentation/package-tree.html).

**Comment by ctrueden** [comment]
Thanks @half-adder. I fixed it.

Note that imagej.net is a wiki, so you can also fix these sorts of things yourself, if you know the fix. In this case, javadoc.imagej.net is now javadoc.scijava.org, but the SSL is not configured yet for javadoc.scijava.org, so the redirect was not working as intended. I'll try to fix this soon.
