### ISSUE TITLE
Trainable Wega Segmentation automated 

### ISSUE THREAD

**Issue by MEKH1** [fiji/Trainable_Segmentation#60]
Hello everyone, 
Where can I find the TWS_automated.bsh? 
I really want this script file so I can import it into the plugin in image j.
Any help will be appreciated

Thanks in advance

**Comment by iarganda** [comment]
Hello @MEKH1 !

I assume you are talking about the script mentioned on https://www.frontiersin.org/articles/10.3389/fendo.2018.00666/full

A year ago I commented to the editors that the supplementary material have wrong file names and extensions. They should be "TWS_automated.bsh" and "Thickness_seperation_automated.txt", while they appear as "Data_Sheet_1_An Optimized Approach to Perform Bone Histomorphometry.CSV" and "Data_Sheet_2_An Optimized Approach to Perform Bone Histomorphometry.CSV".

Just in case, here you are the script and the macro with the right names: https://ehubox.ehu.eus/s/E2tKa5ZiRKFB8Xr

**Comment by MEKH1** [comment]
Hello @iarganda, 
Thanks for your response, you are right I was talking about this paper. 

I am facing another problem maybe it's better to discuss in another thread. 

Regards 
MEKH1
