### ISSUE TITLE
Weka Segmentation Class Colors

### ISSUE THREAD

**Issue by julien2424** [fiji/Trainable_Segmentation#72]
Hello!

We are using Weka Segmentation in a Java application to segment an image and would like to understand how class colors are chosen. When we segment the below image, we get this output after running Weka Segmentation (Class 1 is white, Class 2 is Black, Class 3 is Grey). The output image I get is different than what I get if I run the same process in FIJI so let me know if I'm doing something wrong.

Original:
![original](https://user-images.githubusercontent.com/43152798/157504630-7dd4ba36-5ce1-4419-a96b-a64b9187d0e9.PNG)

Output:
![test_result](https://user-images.githubusercontent.com/43152798/157504679-a2dcb145-68fd-4b13-a555-a810a47a4d8d.jpg)

Code:
```
final ImagePlus imp= new ImagePlus(originalFilepath);
WekaSegmentation original = new WekaSegmentation(imp);
// call method to set class labels
// call method to set examples for 3 classes
original.trainClassifier();
original.applyClassifier( true );
ImagePlus result = original.getClassifiedImage();
```

We need to understand which classes will be what colors, or how we can choose a class's color before segmenting as we will need to threshold the image for the different classes. For example, if we have 4 classes, what will the color of each class be, and what about for 5 classes?

Let me know if you need me to explain or clarify anything. Thanks!

**Comment by frett27** [comment]
Are the images the same resolution in both cases ?

**Comment by julien2424** [comment]
@frett27 After looking at it more, I was able to get my code to return the same image FIJI does (like the image above), but I would still like to know how I could set the colors for different classes. Is this possible?

**Comment by frett27** [comment]
My usage was only binary for classification, so i did not had to interpret
result,
none the less, have you tried activate the probability map ?

on the wekasegmentation code

public ImagePlus applyClassifier(
final ImagePlus imp,
int numThreads,
final boolean *probabilityMaps)*


it seems to create an hyperstack for getting all the classes independently




Le jeu. 10 mars 2022 à 23:09, julien2424 ***@***.***> a
écrit :
